In [880]:
import numpy as np
from collections import Counter
from sklearn.metrics import accuracy_score,confusion_matrix,classification_report

In [881]:
class SVM:
    def __init__(self,learning_rate=0.01, n_iters=1000,lambda_param=0.01):
        self.learning_rate = learning_rate
        self.n_iters = n_iters
        self.lambda_param = lambda_param
        self.weights = None
        self.bias = None
    def fit(self,X,y):
        y_ = np.where(y <= 0, -1, 1)
        n_samples, n_features = X.shape
        self.weights = np.zeros(n_features)
        self.bias = 0
        for i in range(self.n_iters):
            for j, x_i in enumerate(X):
                condition = y_[j] * (np.dot(x_i, self.weights) - self.bias) >= 1
                if condition:
                    self.weights = self.weights - self.learning_rate * (2 * self.lambda_param * self.weights)
                else:
                    self.weights = self.weights - self.learning_rate * (2 * self.lambda_param * self.weights - x_i * y_[j])
                    self.bias = self.bias - self.learning_rate * y_[j]

    def predict(self,X):    
        y_pred = np.dot(X, self.weights) - self.bias
        return np.sign(y_pred)

In [882]:
class My_KNN:
    
    def __init__(self, k=3, distance_metric="euclidean"):
        self.k = k
        self.distance_metric = distance_metric
        
    def fit(self, X, y):
        self.X_train = X
        self.y_train = y 
        
    def euclidean_distance(self, x1, x2):
        return np.sqrt(np.sum((x1 - x2) ** 2))
    
    def manhattan_distance(self, x1, x2):
        return np.sum(np.abs(x1 - x2))
    
    def _distance(self, x1, x2):
        if self.distance_metric == "euclidean":
            return self.euclidean_distance(x1, x2)
        elif self.distance_metric == "manhatan":
            return self.manhattan_distance(x1, x2)
        else:
            raise ValueError("unsupported distance metric please provide either euclidean or manhatan")
    
    def predict(self, X):
        predicted_labels = [self._predict(x) for x in X]
        return np.array(predicted_labels)
    
    def _predict(self, x):
        distances = [self._distance(x, x_train) 
                     for x_train in self.X_train]
        
        k_indices = np.argsort(distances)[:self.k]
        k_nearest_labels = [self.y_train[i] for i in k_indices]
        
        most_common = Counter(k_nearest_labels).most_common(1)
        return most_common[0][0]


In [883]:
def accuracy(y_true, y_pred):
    return np.mean(y_true == y_pred)

In [884]:
#Synthetic Data
X = np.array([
    [2, 2],
    [3, 3],
    [4, 4],
    [5, 5],      # This is Class +1

    [-1, -1],
    [-2, -2],
    [-3, -3],
    [-4, -4]    # This is Class -1
])
y = np.array([1, 1, 1, 1, -1, -1, -1, -1])

In [885]:
svm = SVM(learning_rate=0.01, n_iters=1000, lambda_param=0.01)
svm.fit(X, y)

y_pred_svm = svm.predict(X)
print(y_pred_svm)


[ 1.  1.  1.  1. -1. -1. -1. -1.]


In [886]:
knn = My_KNN(k=3,distance_metric="euclidean")
knn.fit(X,y)

y_pred_knn = knn.predict(X)
print(y_pred_knn)

[ 1  1  1  1 -1 -1 -1 -1]


In [887]:
acc = accuracy_score(y, y_pred_svm)
print("Accuracy:", acc)

Accuracy: 1.0


In [888]:
cm_svm = confusion_matrix(y, y_pred_svm)
print("Confusion Matrix:\n", cm_svm)

Confusion Matrix:
 [[4 0]
 [0 4]]


In [889]:
print(classification_report(y, y_pred_svm))

              precision    recall  f1-score   support

          -1       1.00      1.00      1.00         4
           1       1.00      1.00      1.00         4

    accuracy                           1.00         8
   macro avg       1.00      1.00      1.00         8
weighted avg       1.00      1.00      1.00         8



In [890]:
acc = accuracy_score(y, y_pred_svm)
print("Accuracy:", acc)

Accuracy: 1.0


In [891]:
cm_knn = confusion_matrix(y, y_pred_knn)
print("Confusion Matrix:\n", cm_knn)

Confusion Matrix:
 [[4 0]
 [0 4]]


In [892]:
print(classification_report(y, y_pred_knn))

              precision    recall  f1-score   support

          -1       1.00      1.00      1.00         4
           1       1.00      1.00      1.00         4

    accuracy                           1.00         8
   macro avg       1.00      1.00      1.00         8
weighted avg       1.00      1.00      1.00         8

